import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Background from "../../public/background.jpg";
import { Event, Dinner } from "typings";
import { fetchEvent } from "@/utils/fetchEvents";

type Props = {
  events: Event[];
};

export default function Home({ events }: Props) {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-[90vh] top-0 w-screen bg-cyan-300 static overflow-hidden flex flex-col font-quicksand justify-between">
        <span className="z-10 md:text-6xl text-5xl text-white w-screen md:p-20 p-10">
          We are proud of our Veterans!
        </span>
        <div className="w-full flex justify-center z-10 text-white flex-col items-center">
          <h1 className="md:text-2xl text-xl">Upcoming Events</h1>

          <div className="flex md:flex-row w-screen justify-center flex-wrap items-center">
            {events?.map((event) => (
              <div
                key={event._id}
                className="flex flex-col items-center bg-white text-black m-5 p-2 shadow-2xl rounded-xl w-28 h-28 md:w-50 justify-between md:h-40 text-center"
              >
                <div className="text-[#FF6961] flex flex-col items-center ">
                  <h1 className="text-xl">{event.date.substring(5, 7)}</h1>
                  <h1>{+event.date.substring(8, 10)}</h1>
                </div>
                <div className="text-sm md:text-xl">{event.name}</div>
              </div>
            ))}
          </div>

          <h1 className="text-2xl mt-20">Join one of our active groups</h1>
          <ul className="text-xl flex-start flex flex-col w-max">
            <li>
              <b>Legionnaires</b>
            </li>
            <li>
              <b>Son&aposs of the American Legion</b>
            </li>
            <li>
              <b>Auxiliary</b>
            </li>
          </ul>
        </div>

        <div className="w-screen flex justify-between z-10 md:text-4xl  text-2xl">
          <span className="text-white w-[250px] p-2">
            205 Ley St. Avilla Indiana, 46710
          </span>
          <div className="button-holder z-10 text-black mr-20 bg-[#87CEEB] h-fit md:p-10 p-4 rounded-xl hover:bg-[#113442] hover:text-white">
            <Link href="/contact">Contact us</Link>
          </div>
        </div>
        <div className="absolute h-screen top-0 overflow-hidden">
          <div className="bg-[black]/50 h-full w-full absolute"></div>
          <Image
            src={Background}
            alt=""
            className="h-full object-cover static"
          />
        </div>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const events: Event[] = await fetchEvent();

  return {
    props: {
      events,
    },

    revalidate: 10,
  };
};
